use sysio as io;
use ErrorHandling as ErrH;

fn main(void): void {
	try {
		let a: i32 = 12 / 0;
		io::println(a.to_str());
	} catch(err) {
		ErrH::printerr(err);
	}

	throw(ErrH::new_err("CustomError", "This is a custom error message!"));
}