use sysio as io;
use ErrorHandling as ErrH;

fn main() {
	try {
		let a: int = 12 / 0;
		io::println(a.to_str());
	} catch {
		ErrH::print_err();
	} even {
		io::println("Done!");
	}

	throw(ErrH::new_err("CustomError", "This is a custom error message!"));
}